#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Build

on: [push, pull_request]

jobs:
  image-build:
    strategy:
      matrix:
        dist: [ 'alpine', 'rhel' ]
    runs-on: ubuntu-20.04
    steps:
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: image-build
      run: |
        if [[ "${{matrix.dist}}" == "alpine" ]]; then
          FROM_FILE="Dockerfile"
        elif [[ "${{matrix.dist}}" == "rhel" ]]; then
          FROM_FILE="Dockerfile"
        fi  
        docker pull quay.io/eclipse/che-plugin-registry:nightly
        docker build -f ${FROM_FILE} -t local-plugin-registry .
        docker create --name pluginRegistry local-plugin-registry bash
        mkdir root-dir
        docker cp pluginRegistry:/var/www/html/v3 root-dir/v3
        docker rm -f pluginRegistry
        cp root-dir/v3/plugins/index.json root-dir/index.json
        tar zcvf content-${{matrix.dist}}.tgz -C root-dir .
    - uses: actions/upload-artifact@v2
      with:
        name: plugin-registry-content-${{matrix.dist}}
        path: content-${{matrix.dist}}.tgz
