name: Publish Registry

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  publish:
    if: github.event.workflow_run.event == 'pull_request'
    name: publish
    runs-on: ubuntu-20.04
    steps:
      - name: download dist artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: plugin-registry-content-alpine
          path: content
      - name: PR number
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pull-request-number
      - name: Apply pull request environment
        run: |
          pr_number=$(cat "PR_NUMBER")
          if ! [[ "$pr_number" =~ ^[0-9]+$ ]]; then
            echo "pr number invalid"
            exit 1
          fi
          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: publish
        run: |
          sudo apt-get install tree
          npm install -g surge
          sudo apt-get install tree
          mkdir unpacked
          tar zxvf content/*.tgz -C unpacked/
          ls -la unpacked/
          for directory in `find unpacked/ -type d`
            do
              (cd $directory && tree -H '.' -L 1 --noreport --charset utf-8 | sed '/<p class="VERSION">/,/<\/p>/d' > index.html)
           done
           ls -la unpacked/v3
           cat unpacked/v3/index.html
           export DEPLOY_DOMAIN=https://pr-check-${PR_NUMBER}-che-plugin-registry.surge.sh
           surge ./unpacked --domain $DEPLOY_DOMAIN
           
